---
sudo: required
dist: xenial
language: minimal
before_install:
  - env
  - dpkg -l
  - pip list
  - sudo apt-add-repository --yes ppa:ansible/ansible-2.7
  - sudo apt-get update
  - sudo apt-get install ansible && sudo mkdir -p /etc/ansible/roles
  - sudo echo -e "[defaults]\nhash_behaviour = merge\n" | sudo tee /etc/ansible/ansible.cfg
  - sudo echo -e "localhost ansible_connection=local\n" | sudo tee /etc/ansible/hosts
  - export ANSIBLE_CI_BRANCH=$TRAVIS_BRANCH CI_BUILD_DIR=$TRAVIS_BUILD_DIR ANSIBLE_FORCE_COLOR=1 CI=travis
  - ansible localhost -m setup
install:
  - sudo ln -s $TRAVIS_BUILD_DIR /etc/ansible/roles/mafalb.docker
script:
  - ansible-playbook -t all,debug -bD tests/test.yml -C
  - ansible-playbook -t all,debug -bD tests/test.yml
  - ansible-playbook -t all,debug -bD tests/test.yml | tee /tmp/idempotence.tee
  - "! grep -E 'ok=.*changed=[^0].*unreachable=.*failed=' /tmp/idempotence.tee"
