---
sudo: required
dist: xenial
language: minimal
before_install:
  - env
  - dpkg -l
  - pip list
  - sudo apt-add-repository --yes ppa:ansible/ansible-2.7
  - sudo apt-get update
  - sudo apt-get install ansible
  - export ANSIBLE_CI_BRANCH=$TRAVIS_BRANCH CI_BUILD_DIR=$TRAVIS_BUILD_DIR ANSIBLE_FORCE_COLOR=1 CI=travis
  - ansible localhost -m setup
  - sudo git clone https://github.com/mafalb/ci --recurse-submodules /etc/ansible/roles/mafalb.ci
  - ansible -b -D -t all,debug /etc/ansible/roles/mafalb.ci/before_install.yml
install:
  - ansible -b -D -t all,debug /etc/ansible/roles/mafalb.ci/install.yml
script:
  - ansible-playbook -t all,debug -bD tests/test.yml -C
  - ansible-playbook -t all,debug -bD tests/test.yml
  - ansible-playbook -t all,debug -bD tests/test.yml | tee /tmp/idempotence.tee
  - "! grep -E 'ok=.*changed=[^0].*unreachable=.*failed=' /tmp/idempotence.tee"
