# vim: set ft=yaml ts=2:
---

dist: xenial
language: minimal
env:
  global:
    - ANSIBLE_ROLE_NAME=mafalb.docker
    - CI=travis
    - ANSIBLE_FORCE_COLOR=1
  matrix:
    - targeted_ansible_version: 2.7

before_install:
  - export ANSIBLE_CI_BRANCH=$TRAVIS_BRANCH CI_BUILD_DIR=$TRAVIS_BUILD_DIR
  - env
  - sudo apt-add-repository --yes ppa:ansible/ansible-${targeted_ansible_version} && sudo apt-get update
  - sudo apt-get install ansible
  - sudo pip install ansible-lint
  - dpkg -l
  - pip list
  - ansible --version
  - ansible localhost -m setup
  - ansible-galaxy install -g -r tests/requirements.yml -p roles
  - ansible-playbook -b -D -t all,debug roles/mafalb.ansible_ci/before_install.yml -i cihost, -c local
  - ls -lR
install:
  - ansible-playbook -b -D -t all,debug roles/mafalb.ansible_ci/install.yml
script:
  - ansible-lint --force-color -v tests/test.yml
  - ansible-lint --force-color -v tests/ubuntu.yml
  - ansible-lint --force-color -v tests/idempotency.yml
  - ansible-playbook -t all,debug -D tests/test.yml
  - ansible-playbook -t all,debug -D tests/ubuntu.yml
  - ansible-playbook -t all,debug -D tests/idempotency.yml | tee /tmp/idempotence.tee
  - "! grep -E 'ok=.*changed=[^0].*unreachable=.*failed=' /tmp/idempotence.tee"
after_script:
  - ls -lR
