---
sudo: required
dist: xenial
language: minimal
before_install:
  - env
  - dpkg -l
  - pip list
  - docker --version
  - sudo apt-add-repository --yes ppa:ansible/ansible-2.7
  - sudo apt-get update
  - sudo apt-get install ansible && sudo mkdir -p /etc/ansible/roles
  - sudo echo -e "[defaults]\nhash_behaviour = merge\n" | sudo tee /etc/ansible/ansible.cfg
  - sudo echo -e "localhost ansible_connection=local\n" | sudo tee /etc/ansible/hosts
  - ansible localhost -m setup
  - ansible --version
install:
  - pwd
  - sudo ln -s $TRAVIS_BUILD_DIR /etc/ansible/roles/docker
script:
  - ansible-playbook --become -D tests/test.yml -C -t all,debug
  - ansible-playbook --become -D tests/test.yml    -t all,debug
after_script:
  - docker version
