# vi: set ft=yaml ts=2:
---

- name: assertions
  assert:
    that:
      - ansible_distribution == "Ubuntu"

- name: docker repo does exist
  when: ansible_distribution == "Ubuntu"
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    update_cache: true
    state: present
