# vim: set ft=yaml ts=2:
---

- name: debug docker
  debug: var=docker
  tags:
    - never
    - debug

- name: docker-ce repo does exist
  when:
    - not docker.assume_already_installed
    - docker.package == "docker-ce"
  include_tasks:
    file: docker-ce.yml

- name: include apt specific stuff if necessary
  when: ansible_pkg_mgr == 'apt'
  include_tasks:
    file: apt.yml

- name: docker daemon does exist
  when: not docker.assume_already_installed
  package:
    name: "{{ docker.package }}"
    state: present

- name: docker service is running
  when: not ansible_virtualization_type == 'docker'
  service:
    name: "{{ docker.service }}"
    state: started
    enabled: true
