# vi: set ft=yaml ts=2:
---

- name: python-docker does exist
  when: docker.ansible.package
  package:
    name: "{{ docker.ansible.package }}"
    state: "{{ docker.ansible.package|ternary('present','absent') }}"

# this is a dirty hack for ubuntu xenial 16
- name: python-docker does not exist
  when: not docker.ansible.package
  pip:
    name: docker
    state: present
